package com.production.production_system.mapper;

import com.production.production_system.dto.MachineDTO;
import com.production.production_system.entity.Machine;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
public class MachineConverter {

    private final ModelMapper modelMapper;

    public MachineDTO toDto(Machine machine) {
        // All fields match 1-to-1 (id, nom, etat, maintenanceProchaine)
        return modelMapper.map(machine, MachineDTO.class);
    }

    public Machine toEntity(MachineDTO dto) {
        Machine machine = modelMapper.map(dto, Machine.class);
        machine.setId(null); // id is generated by the DB
        return machine;
    }
}